package messaging

import (
	"bytes"
	"context"
	"errors"
	"slices"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Kind int16

const (
	// KindEnvelope is a client envelope: a message, receipt or anything else
	// clients encode in the opaque payload.
	KindEnvelope Kind = 1
	// KindDelivered is generated by the server when the recipient acknowledges
	// a client envelope; RefMessageID names it. The server knows delivery
	// happened anyway, so this reveals nothing new to it.
	KindDelivered Kind = 2
)

type Envelope struct {
	Seq            int64
	MessageID      uuid.UUID
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	RecipientID    uuid.UUID
	Kind           Kind
	RefMessageID   uuid.NullUUID
	ClientTS       time.Time
	ServerTS       time.Time
	Payload        []byte
}

var (
	ErrUnknownRecipient = errors.New("messaging: unknown recipient")
	// ErrRecipientFull: the sender already has MaxUndelivered envelopes
	// waiting for this recipient.
	ErrRecipientFull = errors.New("messaging: too many undelivered envelopes for this recipient")
)

// MaxUndelivered bounds the client envelopes one sender may have queued for
// one recipient, so a single account cannot fill another's queue. Server
// delivery receipts are not counted.
const MaxUndelivered = 1000

type Store interface {
	// Accept persists e. If (sender, message_id) was accepted before, nothing
	// is stored and the original seq/server_ts are returned with dup=true.
	Accept(ctx context.Context, e Envelope) (stored Envelope, dup bool, err error)
	// AcceptMulti persists one copy of e per recipient (group fan-out) in one
	// transaction, under a single dedup tombstone for (sender, message_id).
	// The returned envelope carries the first copy's seq. recipients must be
	// distinct; an unknown recipient fails the whole send.
	AcceptMulti(ctx context.Context, e Envelope, recipients []uuid.UUID) (stored Envelope, dup bool, err error)
	// Pending returns the recipient's envelopes with seq > after, in seq order.
	Pending(ctx context.Context, recipient uuid.UUID, after int64, limit int) ([]Envelope, error)
	// Ack deletes the recipient's envelope seq. For client envelopes it
	// atomically queues a KindDelivered receipt to the sender and returns it.
	// Acking an unknown or already-acked seq is a no-op.
	Ack(ctx context.Context, recipient uuid.UUID, seq int64, now time.Time) (*Envelope, error)
	// Purge deletes undelivered envelopes and dedup tombstones older than before.
	Purge(ctx context.Context, before time.Time) error
}

type PGStore struct {
	pool  *pgxpool.Pool
	quota int
}

func NewPGStore(pool *pgxpool.Pool) *PGStore { return &PGStore{pool: pool, quota: MaxUndelivered} }

// WithQuota returns a copy with a different undelivered quota (tests).
func (s *PGStore) WithQuota(n int) *PGStore { return &PGStore{pool: s.pool, quota: n} }

// checkQuota must run under the recipient's lock. The count stops at
// quota+1 rows, so its cost is bounded however full the queue is.
func (s *PGStore) checkQuota(ctx context.Context, tx pgx.Tx, sender, recipient uuid.UUID) error {
	var n int
	err := tx.QueryRow(ctx, `
		SELECT count(*) FROM (
			SELECT 1 FROM envelopes WHERE recipient_id = $1 AND sender_id = $2 AND kind = 1 LIMIT $3
		) q`, recipient, sender, s.quota+1).Scan(&n)
	if err != nil {
		return err
	}
	if n >= s.quota {
		return ErrRecipientFull
	}
	return nil
}

var _ Store = (*PGStore)(nil)

func (s *PGStore) Accept(ctx context.Context, e Envelope) (Envelope, bool, error) {
	var stored Envelope
	var dup bool
	err := pgx.BeginFunc(ctx, s.pool, func(tx pgx.Tx) error {
		// Serialize inserts per recipient so seq order equals commit order.
		// Without this, two concurrent senders could commit seq 11 before 10
		// and a delivery cursor that already passed 11 would skip 10.
		if err := lockRecipient(ctx, tx, e.RecipientID); err != nil {
			return err
		}
		if dupStored, ok, err := lookupAccepted(ctx, tx, e); err != nil || ok {
			if ok {
				dup, stored = true, dupStored
			}
			return err
		}
		if err := s.checkQuota(ctx, tx, e.SenderID, e.RecipientID); err != nil {
			return err
		}
		var seq int64
		err := tx.QueryRow(ctx, `
			INSERT INTO accepted_messages (sender_id, message_id, seq, server_ts)
			VALUES ($1, $2, nextval(pg_get_serial_sequence('envelopes', 'seq')), $3)
			ON CONFLICT (sender_id, message_id) DO NOTHING
			RETURNING seq`,
			e.SenderID, e.MessageID, e.ServerTS,
		).Scan(&seq)
		if errors.Is(err, pgx.ErrNoRows) {
			dup = true
			stored = e
			return tx.QueryRow(ctx, `
				SELECT seq, server_ts FROM accepted_messages WHERE sender_id = $1 AND message_id = $2`,
				e.SenderID, e.MessageID,
			).Scan(&stored.Seq, &stored.ServerTS)
		}
		if err != nil {
			return err
		}
		e.Seq = seq
		if err := insertEnvelope(ctx, tx, e); err != nil {
			return err
		}
		stored = e
		return nil
	})
	if isForeignKeyViolation(err) {
		return Envelope{}, false, ErrUnknownRecipient
	}
	return stored, dup, err
}

func (s *PGStore) AcceptMulti(ctx context.Context, e Envelope, recipients []uuid.UUID) (Envelope, bool, error) {
	// Lock recipients in a fixed order so concurrent fan-outs to
	// overlapping sets can't deadlock.
	sorted := slices.Clone(recipients)
	slices.SortFunc(sorted, func(a, b uuid.UUID) int { return bytes.Compare(a[:], b[:]) })
	var stored Envelope
	var dup bool
	err := pgx.BeginFunc(ctx, s.pool, func(tx pgx.Tx) error {
		for _, r := range sorted {
			if err := lockRecipient(ctx, tx, r); err != nil {
				return err
			}
		}
		if dupStored, ok, err := lookupAccepted(ctx, tx, e); err != nil || ok {
			if ok {
				dup, stored = true, dupStored
			}
			return err
		}
		for _, r := range sorted {
			if err := s.checkQuota(ctx, tx, e.SenderID, r); err != nil {
				return err
			}
		}
		var first int64
		err := tx.QueryRow(ctx, `
			INSERT INTO accepted_messages (sender_id, message_id, seq, server_ts)
			VALUES ($1, $2, nextval(pg_get_serial_sequence('envelopes', 'seq')), $3)
			ON CONFLICT (sender_id, message_id) DO NOTHING
			RETURNING seq`,
			e.SenderID, e.MessageID, e.ServerTS,
		).Scan(&first)
		if errors.Is(err, pgx.ErrNoRows) {
			dup = true
			stored = e
			return tx.QueryRow(ctx, `
				SELECT seq, server_ts FROM accepted_messages WHERE sender_id = $1 AND message_id = $2`,
				e.SenderID, e.MessageID,
			).Scan(&stored.Seq, &stored.ServerTS)
		}
		if err != nil {
			return err
		}
		for i, r := range sorted {
			c := e
			c.RecipientID = r
			c.Seq = first
			if i > 0 {
				if err := tx.QueryRow(ctx, `SELECT nextval(pg_get_serial_sequence('envelopes', 'seq'))`).Scan(&c.Seq); err != nil {
					return err
				}
			}
			if err := insertEnvelope(ctx, tx, c); err != nil {
				return err
			}
		}
		e.Seq = first
		stored = e
		return nil
	})
	if isForeignKeyViolation(err) {
		return Envelope{}, false, ErrUnknownRecipient
	}
	return stored, dup, err
}

func (s *PGStore) Pending(ctx context.Context, recipient uuid.UUID, after int64, limit int) ([]Envelope, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT seq, message_id, conversation_id, sender_id, recipient_id, kind, ref_message_id, client_ts, server_ts, payload
		FROM envelopes WHERE recipient_id = $1 AND seq > $2 ORDER BY seq LIMIT $3`,
		recipient, after, limit)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, func(r pgx.CollectableRow) (Envelope, error) {
		var e Envelope
		err := r.Scan(&e.Seq, &e.MessageID, &e.ConversationID, &e.SenderID, &e.RecipientID, &e.Kind,
			&e.RefMessageID, &e.ClientTS, &e.ServerTS, &e.Payload)
		return e, err
	})
}

func (s *PGStore) Ack(ctx context.Context, recipient uuid.UUID, seq int64, now time.Time) (*Envelope, error) {
	var receipt *Envelope
	err := pgx.BeginFunc(ctx, s.pool, func(tx pgx.Tx) error {
		var acked Envelope
		err := tx.QueryRow(ctx, `
			DELETE FROM envelopes WHERE seq = $1 AND recipient_id = $2
			RETURNING message_id, conversation_id, sender_id, kind`,
			seq, recipient,
		).Scan(&acked.MessageID, &acked.ConversationID, &acked.SenderID, &acked.Kind)
		if errors.Is(err, pgx.ErrNoRows) {
			return nil // already acked, or not this recipient's
		}
		if err != nil {
			return err
		}
		if acked.Kind != KindEnvelope {
			return nil
		}
		r := Envelope{
			MessageID:      uuid.New(),
			ConversationID: acked.ConversationID,
			SenderID:       recipient,
			RecipientID:    acked.SenderID,
			Kind:           KindDelivered,
			RefMessageID:   uuid.NullUUID{UUID: acked.MessageID, Valid: true},
			ClientTS:       now,
			ServerTS:       now,
			Payload:        []byte{},
		}
		if err := lockRecipient(ctx, tx, r.RecipientID); err != nil {
			return err
		}
		if err := tx.QueryRow(ctx, `SELECT nextval(pg_get_serial_sequence('envelopes', 'seq'))`).Scan(&r.Seq); err != nil {
			return err
		}
		if err := insertEnvelope(ctx, tx, r); err != nil {
			return err
		}
		receipt = &r
		return nil
	})
	return receipt, err
}

func (s *PGStore) Purge(ctx context.Context, before time.Time) error {
	if _, err := s.pool.Exec(ctx, `DELETE FROM envelopes WHERE server_ts < $1`, before); err != nil {
		return err
	}
	_, err := s.pool.Exec(ctx, `DELETE FROM accepted_messages WHERE server_ts < $1`, before)
	return err
}

// lookupAccepted reports a retried send: a duplicate is acknowledged with
// its original seq even when the quota is now full.
func lookupAccepted(ctx context.Context, tx pgx.Tx, e Envelope) (Envelope, bool, error) {
	stored := e
	err := tx.QueryRow(ctx, `
		SELECT seq, server_ts FROM accepted_messages WHERE sender_id = $1 AND message_id = $2`,
		e.SenderID, e.MessageID,
	).Scan(&stored.Seq, &stored.ServerTS)
	if errors.Is(err, pgx.ErrNoRows) {
		return Envelope{}, false, nil
	}
	return stored, err == nil, err
}

func lockRecipient(ctx context.Context, tx pgx.Tx, recipient uuid.UUID) error {
	_, err := tx.Exec(ctx, `SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))`, recipient)
	return err
}

func insertEnvelope(ctx context.Context, tx pgx.Tx, e Envelope) error {
	_, err := tx.Exec(ctx, `
		INSERT INTO envelopes (seq, message_id, conversation_id, sender_id, recipient_id, kind, ref_message_id, client_ts, server_ts, payload)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)`,
		e.Seq, e.MessageID, e.ConversationID, e.SenderID, e.RecipientID, e.Kind, e.RefMessageID, e.ClientTS, e.ServerTS, e.Payload)
	return err
}

func isForeignKeyViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23503"
}
