package dev.whispr.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Generated from seed #2F6F8F with Material Color Utilities (SchemeTonalSpot,
// standard contrast). Regenerate rather than hand-editing individual values;
// ColorContrastTest guards the text/background pairs.
// This file is the only place raw color values may appear.

internal val lightPrimary = Color(0xFF1D6586)
internal val lightOnPrimary = Color(0xFFFFFFFF)
internal val lightPrimaryContainer = Color(0xFFC4E7FF)
internal val lightOnPrimaryContainer = Color(0xFF004C69)
internal val lightInversePrimary = Color(0xFF90CEF4)
internal val lightSecondary = Color(0xFF4E616D)
internal val lightOnSecondary = Color(0xFFFFFFFF)
internal val lightSecondaryContainer = Color(0xFFD1E5F4)
internal val lightOnSecondaryContainer = Color(0xFF374955)
internal val lightTertiary = Color(0xFF615A7D)
internal val lightOnTertiary = Color(0xFFFFFFFF)
internal val lightTertiaryContainer = Color(0xFFE6DEFF)
internal val lightOnTertiaryContainer = Color(0xFF494264)
internal val lightBackground = Color(0xFFF6FAFE)
internal val lightOnBackground = Color(0xFF181C1F)
internal val lightSurface = Color(0xFFF6FAFE)
internal val lightOnSurface = Color(0xFF181C1F)
internal val lightSurfaceVariant = Color(0xFFDDE3EA)
internal val lightOnSurfaceVariant = Color(0xFF41484D)
internal val lightSurfaceTint = Color(0xFF1D6586)
internal val lightInverseSurface = Color(0xFF2C3134)
internal val lightInverseOnSurface = Color(0xFFEDF1F5)
internal val lightError = Color(0xFFBA1A1A)
internal val lightOnError = Color(0xFFFFFFFF)
internal val lightErrorContainer = Color(0xFFFFDAD6)
internal val lightOnErrorContainer = Color(0xFF93000A)
internal val lightOutline = Color(0xFF71787D)
internal val lightOutlineVariant = Color(0xFFC0C7CD)
internal val lightScrim = Color(0xFF000000)
internal val lightSurfaceBright = Color(0xFFF6FAFE)
internal val lightSurfaceDim = Color(0xFFD7DADF)
internal val lightSurfaceContainer = Color(0xFFEAEEF3)
internal val lightSurfaceContainerHigh = Color(0xFFE5E8ED)
internal val lightSurfaceContainerHighest = Color(0xFFDFE3E7)
internal val lightSurfaceContainerLow = Color(0xFFF0F4F8)
internal val lightSurfaceContainerLowest = Color(0xFFFFFFFF)
internal val darkPrimary = Color(0xFF90CEF4)
internal val darkOnPrimary = Color(0xFF00344A)
internal val darkPrimaryContainer = Color(0xFF004C69)
internal val darkOnPrimaryContainer = Color(0xFFC4E7FF)
internal val darkInversePrimary = Color(0xFF1D6586)
internal val darkSecondary = Color(0xFFB5C9D7)
internal val darkOnSecondary = Color(0xFF20333E)
internal val darkSecondaryContainer = Color(0xFF374955)
internal val darkOnSecondaryContainer = Color(0xFFD1E5F4)
internal val darkTertiary = Color(0xFFCAC1E9)
internal val darkOnTertiary = Color(0xFF322C4C)
internal val darkTertiaryContainer = Color(0xFF494264)
internal val darkOnTertiaryContainer = Color(0xFFE6DEFF)
internal val darkBackground = Color(0xFF0F1417)
internal val darkOnBackground = Color(0xFFDFE3E7)
internal val darkSurface = Color(0xFF0F1417)
internal val darkOnSurface = Color(0xFFDFE3E7)
internal val darkSurfaceVariant = Color(0xFF41484D)
internal val darkOnSurfaceVariant = Color(0xFFC0C7CD)
internal val darkSurfaceTint = Color(0xFF90CEF4)
internal val darkInverseSurface = Color(0xFFDFE3E7)
internal val darkInverseOnSurface = Color(0xFF2C3134)
internal val darkError = Color(0xFFFFB4AB)
internal val darkOnError = Color(0xFF690005)
internal val darkErrorContainer = Color(0xFF93000A)
internal val darkOnErrorContainer = Color(0xFFFFDAD6)
internal val darkOutline = Color(0xFF8B9297)
internal val darkOutlineVariant = Color(0xFF41484D)
internal val darkScrim = Color(0xFF000000)
internal val darkSurfaceBright = Color(0xFF353A3D)
internal val darkSurfaceDim = Color(0xFF0F1417)
internal val darkSurfaceContainer = Color(0xFF1C2023)
internal val darkSurfaceContainerHigh = Color(0xFF262B2E)
internal val darkSurfaceContainerHighest = Color(0xFF313539)
internal val darkSurfaceContainerLow = Color(0xFF181C1F)
internal val darkSurfaceContainerLowest = Color(0xFF0A0F12)
